# This file was generated by GoReleaser. DO NOT EDIT.
cask "nanoproxy" do
  name "nanoproxy"
  desc "Simple Socks5 Proxy written in Go"
  homepage "https://github.com/ryanbekhen/nanoproxy"
  version "0.15.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nanoproxy"

  on_macos do
    on_intel do
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v#{version}/nanoproxy_Darwin_x86_64.tar.gz"
      sha256 "8aafc9e402e53a157f72ec1a4876a7f283ff31fee226a5cd0b0a8441a24580f5"
    end
    on_arm do
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v#{version}/nanoproxy_Darwin_arm64.tar.gz"
      sha256 "0864d6a30da3492a73514efaf9e7acdf99b2130e283708e1409fabeab54f0b23"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v#{version}/nanoproxy_Linux_x86_64.tar.gz"
      sha256 "322e883283abf3fa0cccaf70a4ed02c0ff1840c27912e983d7b29a36e2b3f24c"
    end
    on_arm do
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v#{version}/nanoproxy_Linux_arm64.tar.gz"
      sha256 "f6c122ac30b10fd18643d084e2e11742818b20f49d59c769fbe37dd849539db9"
    end
  end

  postflight do
    bin.install "nanoproxy"
  end

  # No zap stanza required
end
