# This file was generated by GoReleaser. DO NOT EDIT.
cask "nanoproxy" do
  version "0.17.3"

  on_macos do
    on_intel do
      sha256 "a126505abc0535efd1b3b6c14de77673868de561de4c796e60ed582c562ac7da"
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v#{version}/nanoproxy_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "720d6410f43f75aa4d4a28eeb0145ea7f53007bdc78241a16d02946a07bf7ec2"
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v#{version}/nanoproxy_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "588a63fb09efdc6c95d39c2008223b35d8b59a43c0767bfe4241459af1981025"
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v#{version}/nanoproxy_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "74a7872a5c7b19f022f943c31d84e6b483ab135ad03ee328462bc776c2e85151"
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v#{version}/nanoproxy_Linux_arm64.tar.gz"
    end
  end

  name "nanoproxy"
  desc "Simple Socks5 Proxy written in Go"
  homepage "https://github.com/ryanbekhen/nanoproxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nanoproxy"

  # No zap stanza required

end
