# This file was generated by GoReleaser. DO NOT EDIT.
cask "nanoproxy" do
  name "nanoproxy"
  desc "Simple Socks5 Proxy written in Go"
  homepage "https://github.com/ryanbekhen/nanoproxy"
  version "0.15.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nanoproxy"

  on_macos do
    on_intel do
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v#{version}/nanoproxy_Darwin_x86_64.tar.gz"
      sha256 "88063b99ec555d58efe94100b06f92e06245b909e51bff54f0aa5a2574ef22fd"
    end
    on_arm do
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v#{version}/nanoproxy_Darwin_arm64.tar.gz"
      sha256 "0215a2963ebeff8fdee44c0a1d92ab68184c3f01b5869dd9c5548dcae1395615"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v#{version}/nanoproxy_Linux_x86_64.tar.gz"
      sha256 "5edc3e1fe6850dcfd9e2d5134e1dfcdc19c1414bdadf9e2f46de218c8107c4ba"
    end
    on_arm do
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v#{version}/nanoproxy_Linux_arm64.tar.gz"
      sha256 "bd3382f666624b9da8abf5e7a73534c682c6d7e66ab798efd0189d213affed86"
    end
  end

  # No zap stanza required
end
