# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanoproxy < Formula
  desc "Simple Socks5 Proxy written in Go"
  homepage "https://github.com/ryanbekhen/nanoproxy"
  version "0.13.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.13.2/nanoproxy_Darwin_x86_64.tar.gz"
      sha256 "785d5ebae0c45d06141ff53c3ea7a33d915fad81802f8a7c0d88d52aead4d91a"

      def install
        bin.install "nanoproxy"
      end
    end
    on_arm do
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.13.2/nanoproxy_Darwin_arm64.tar.gz"
      sha256 "24b39211dab1ca04b99053c951a3dfbb12569479d876f4f503382861f0f3027b"

      def install
        bin.install "nanoproxy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.13.2/nanoproxy_Linux_x86_64.tar.gz"
        sha256 "5ab30ec832e40ae03847e3ee6ab14254a6e178963296b616effd50773c96eef7"

        def install
          bin.install "nanoproxy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.13.2/nanoproxy_Linux_arm64.tar.gz"
        sha256 "37e0c3811b738d13a0f386a9c3de0c65c10fac657544bc8a3cb9759769dc0884"

        def install
          bin.install "nanoproxy"
        end
      end
    end
  end
end
